apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app_namespace }}
  name: {{ .Values.name }}
  labels:
    service: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer