name: server

app_namespace: app

environment: dev

replicas: 1

image:
  repository: saifhub
  name: app_project
  tag: v0.0.1

flask_env: development


secrets:
  postgresql:
    user: ""
    database: ""
    password: ""

postgresql:
  host: bitnami-postgresql.db.svc.cluster.local

resources:
  requests:
    cpu: 200m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 512Mi