name: server

app_namespace: app

environment: prod

replicas: 3

image:
  repository: saifhub
  name: app_project
  tag: 1

flask_env: development


secrets:
  postgresql:
    user: ""
    database: ""
    password: ""

postgresql:
  host: bitnami-postgresql.apit.svc.cluster.local

resources:
  requests:
    cpu: 200m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 512Mi